NORMALIDAD = [
    "NORMAL", 
    "ANORMAL"
]

SINO = [
    "NO",
    "SI"
]

REFERENCIA = [
    "NO REFIERE",
    "REFIERE"
]

APROBACION = [
    "APROBADO",
    "NO APROBADO"
]

ANTECEDENTES_FAMILIARES = [
    "N/A",
    "ENFERMEDADES CARDIOVASCULARES",
    "ENFERMEDADES CONGENITAS"
    "ENFERMEDADES DE TRASMISION SEXUAL",
    "ENFERMEDADES DEL SISTEMA LOCOMOTOR",
    "ENFERMEDADES DEL SISTEMA NERVIOSO",
    "ENFERMEDADES DERMATOLOGICAS",
    "ENFERMEDADES ENDOCRINOLOGICA",
    "ENFERMEDADES GASTROINTESTINALES",
    "ENFERMEDADES GENITOURINARI",
    "ENFERMEDADES INFECCIOSAS Y PARASITARIAS",
    "ENFERMEDADES INMUNOLOGICA",
    "ENFERMEDADES MENTALES",
    "ENFERMEDADES ONCOLOGICAS",
    "ENFERMEDADES RESPIRATORIAS"
]

EQUIPOS_UTILIZADOS = [
    "N/A",
    "COMPUTADOR",
    "TELEFONO",
    "MAQUINAS",
    "HERRAMIENTAS MANUALES",
    "HERAMIENTAS MECANICAS",
    "OTRAS HERRAMIENTAS"
]

REMITIDO = [
    "N/A",
    "E.P.S",
    "A.R.L",
    "ESPECIALISTA",
    "OTRO",
    "PSICOLOGIA",
    "PSIQUIATRIA",
    "AUDIOLOGIA",
    "FONOLOGIA",
    "OPTOMETRIA",
    "OFTALMOLOGIA",
    "ORTOPTICA",
    "OTORRINOLARINGOLOGO",
]

LARSEN = [
    "NORMAL",
    "GRADO I",
    "GRADO II",
    "GRADO III"
]

HZ = [
    "125 HZ",
    "0 HZ",
    "250 HZ",
    "500 HZ",
    "1000 HZ",
    "8000 HZ",
    "2000 HZ",
    "4000 HZ"
]

WEBER = [
    "INDIFERENTE",
    "LATERALIZA OD",
    "LATERALIZA OI",
    "NO LATERALIZA"
]

CONDUCTO = [
    "NORMAL",
    "TAPON TOTAL CERUMEN",
    "TAPON PARCIAL CERUMEN",
    "DESCAMACIÓN",
    "ERITEMA",
    "SECRECIONES",
    "OTOMICOSIS",
    "OTITIS",
    "CUERPO EXTRAÑO"
]

MEMBRANA = [
    "NORMAL",
    "OPACA",
    "PERFORACIÓN",
    "INCONTINUA",
    "ABOMBAMIENTO",
    "PLACAS",
    "TUBO DE VENTILACIÓN",
    "SECRECIONES",
    "NO SE OBSERVA"
]

AGUDEZA_VISUAL = [
    "20/20",
    "20/25",
    "20/30",
    "20/40",
    "20/50",
    "20/70",
    "20/80",
    "20/100",
    "20/200"
]

TIEMPO = [
    "NO REFIERE",
    "MENOR 1 AÑO",
    "1 AÑO",
    "1 A 2 AÑOS",
    "2 A 3 AÑOS",
    "(+) DE 3 AÑOS"
]

LENSOMETRIA = [
    "+1.00",
    "+1.25",
    "+1.50",
    "+1.75",
    "+2.00",
    "+2.25",
    "+2.50",
    "+2.75",
    "+3.00"
]

FACTURA = [
    "EXAMEN MEDICO OCUPACIONAL",
    "EXAMEN PSCIOLOGIA OCUPACIONAL",
    "EXAMEN FONOAUDIOLOGIA OCUPACIONAL",
    "EXAMEN OPTOMETRIA OCUPACIONAL",
    "EXAMEN OCUPACIONAL",
    "COPIA CERTIFICADO OCUPACIONAL"
]

VALOR_FACTURA = [
    "$0",
    "$180.000,00",
    "$90.000,00",
    "$60.000,00",
    "$30.000,00"
]

PATOLOGICOS = [
    "NO REFIERE",
    "ENFERMEDADES CARDIOVASCULARES",
    "ENFERMEDADES CONGENITAS",
    "ENFERMEDADES DE TRASMISION SEXUAL",
    "ENFERMEDADES DEL SISTEMA LOCOMOTOR",
    "ENFERMEDADES DEL SISTEMA NERVIOSO",
    "ENFERMEDADES DERMATOLOGICAS",
    "ENFERMEDADES ENDOCRINOLOGICAS",
    "ENFERMEDADES GASTROINTESTINALES",
    "ENFERMEDADES GENITOURINARIO",
    "ENFERMEDADES INFECCIOSAS Y PARASITARIAS",
    "ENFERMEDADES INMUNOLOGICAS",
    "ENFERMEDADES MENTALES",
    "ENFERMEDADES ONCOLOGICAS",
    "ENFERMEDADES RESPIRATORIAS"
]

ETS = [
    "NO REFIERE",
    "SÍFILIS",
    "GONOCOCIA",
    "CHANCRO BLANDO",
    "GRANULOMA INGUINAL",
    "LINFOGRANULOMA VENÉREO",
    "URETRITIS Y CERVICITIS",
    "VAGINOSIS BACTERIANA",
    "HERPES GENITAL",
    "CONDILOMAS ACUMINADOS",
    "MOLLUSCUM CONTAGIOSO",
    "HEPATITIS B, C, D, E Y G",
    "ENFERMEDAD PERINATAL",
    "SIDA (VIH 1 Y 2)",
    "VAGINITIS Y URETRITIS",
    "VULVOVAGINITIS Y BALANOPOSTITIS",
    "PEDICULOSIS PÚBICA",
    "SARNA"
]

NRO_VACUNA = [
    "PRIMERA",
    "SEGUNDA",
    "TERCERA",
    "REFUERZO",
    "N/A"
]