version: '2.1'

volumes:
  auth_microservice_database_sips:
  clinical_microservices_database_sips:

networks:
  auth:
  clinical:

services:
  auth_microservice_database-sips:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: auth
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - auth_microservice_database_sips:/var/lib/mysql
    restart: always
    container_name: auth_microservice_database_sips
    networks:
      - auth

  clinical_microservice_database_sips:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: solution
      MYSQL_DATABASE: solution
    ports:
      - "3307:3306"
    volumes:
      - clinical_microservices_database_sips:/var/lib/mysql
    restart: always
    container_name: clinical_microservices_database_sips
    networks:
      - clinical
