CREATE TABLE `Auth`.`paciente` (
  `documento` VARCHAR(20) NOT NULL,
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `edad` INT NOT NULL,
  `nacionalidad` VARCHAR(3) NOT NULL,
  `lugarNacimiento` VARCHAR(3) NOT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `celular` VARCHAR(30) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `fechaIngreso` DATE,
  `tiempoCargo` VARCHAR(50) NOT NULL,
  `arl` VARCHAR(45) NOT NULL,
  `eps` VARCHAR(45) NOT NULL,
  `afp` VARCHAR(45) NOT NULL,
  `telefonoEmpresa` VARCHAR(45),
  `observaciones` VARCHAR(500) NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `join_at` DATETIME NOT NULL,
  `last_login` DATETIME DEFAULT NULL,
  PRIMARY KEY (`documento`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE);