from marshmallow import Schema, fields
from marshmallow import validate

class CreateRegisterMedicoSchema(Schema):
    tipo_documento = fields.Str(required=True, validate=lambda x: True if x in ["CC", "TI", "RC", "CE"] else False)
    documento = fields.Str(required=True, validate=validate.Length(min=1, max=12))
    nombres = fields.Str(required=True, validate=validate.Length(max=100))
    apellidos = fields.Str(required=True, validate=validate.Length(max=100))
    fecha_nacimiento = fields.Date(required=True)
    lugar_nacimiento = fields.Str(required=True, validate=validate.Length(equal=3))
    nacionalidad = fields.Str(required=True, validate=validate.Length(equal=3))
    genero = fields.Str(required=True, validate=validate.ContainsOnly(['M', 'F', 'O']))
    direccion = fields.Str(required=True, validate=validate.Length(min=1, max=100))
    telefono = fields.Str(required=True, validate=validate.Length(min=1, max=15))
    salario = fields.Number(required=True)
    tp = fields.Str(required=True)
    arl = fields.Str(required=True, validate=validate.Length(min=1, max=100))
    eps = fields.Str(required=True, validate=validate.Length(min=1, max=100))
    afp = fields.Str(required=True, validate=validate.Length(min=1, max=100))
    rethus = fields.Str(required=True)
    secretaria_salud = fields.Str(required=True)
    correo = fields.Str(required=True, validate=validate.Email())
    password = fields.Str(required=True, validate=validate.Length(max=200))
    rol = fields.Str(required=True, validate=validate.Length(max=20))
    foto = fields.Str(required=False, validate=validate.Length(max=150))
