version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - ./db_data:/var/lib/mysql
