from marshmallow import Schema, fields
from marshmallow import validate
from src.models.anexos import anexos as a

class HistoriaPsicologiaSchema(Schema):
    estado = fields.Bool(required=True)
    documento_paciente = fields.Str(required=True, validate=validate.Length(min=1, max=20))
    ant_tra = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ant_enf = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ant_sueño = fields.Str(required=True, validate=lambda x: x in a.SINO)
    obs_cond_pres = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_post = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_disc = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_tono = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_arti = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_orien_tiem = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_orien_esp = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    obs_cond_orien_perso = fields.Str(required=True, validate=lambda x: x in a.ADECUACION)
    ries_emp_gest_org = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_carac_org = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_tare = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_grup = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_interf = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_jorna = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_cond = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_carga = fields.Str(required=True, validate=lambda x: x in a.SINO)
    ries_emp_obs = fields.Str(required=True, validate=validate.Length(max=500))
    histo_famili = fields.Str(required=True, validate=validate.Length(max=500))
    cie_concep_desc = fields.Str(required=True, validate=validate.Length(max=500))
    cie_concep_reco = fields.Str(required=True, validate=validate.Length(max=300))
    cie_concep_aplaz = fields.Str(required=True, validate=validate.Length(max=300))
    cie_concep_reco_mot = fields.Str(required=True, validate=lambda x: x in a.REMITIDO)
    cie_obs = fields.Str(required=True, validate=validate.Length(max=500))
    cie_concep_fin = fields.Str(required=True, validate=lambda x: x in a.APROBACION)
    psicosensomotriz = fields.Str(required=True, validate=lambda x: x in a.APROBACION)
    personalidad = fields.Str(required=True, validate=lambda x: x in a.APROBACION)
    inteligencia = fields.Str(required=True, validate=lambda x: x in a.APROBACION)